name: meal_finder
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed: ^2.4.1
  dio: ^5.3.0
  either_dart: ^1.0.0
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  provider: ^6.0.5
  auto_size_text: ^3.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  flutter_blurhash: ^0.7.0
  bloc_test: ^9.1.4
  mocktail: ^1.0.0
  google_fonts: ^5.1.0
  logger: ^2.0.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
